apiVersion: v1
kind: ReplicationController
metadata:
    name: mywebapp
spec:
 replicas: 1
 selector:
  app: mywebapp
 template:
   metadata:
     labels:
         app: mywebapp
   spec:
     containers:
     - name: mywebapp
       image: sureshaho/mywebapp
       ports:
       - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
    name: mywebapp
spec:
  type: ClusterIP
  selector:
    app: mywebapp
  ports:
  - port: 80
    targetPort: 8080
